spring:
  #配置数据源
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/centerim_avatar?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 176318surelan
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minIdle: 2
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    #exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat #,wall,sl4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
server:
   port: 8080

mybatis:
  typeAliasesPackage: com.lanfangyi.nettyim.bean #这里配置实体对应的包路径
  mapperLocations: classpath:mapper/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制打印sql语句

# druid后台地址：http://localhost:8080/druid/datasource.html 神奇，只有谷歌浏览器能打开这个页面 http://localhost:8080/druid/index.html
# 账号密码均为：lanfangyi@haodf.com



